[package]
name = "shader_def"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
proc-macro = true

[dependencies]
glsl = "6.0.2"
quote = "1.0.33"
syn = "2.0.39"
